[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "aiaccel"
version = "2.0.0"
description = "A library for accelerating research on ABCI"
readme = "README.md"
requires-python = ">=3.8.1,<3.12"
license = {text = "MIT"}
authors = [
    {name = "AIST", email = "onishi-masaki@aist.go.jp"}
]
classifiers = [
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "numpy",
    "lightning",
    "hydra-core",
    "torch",
    "omegaconf",
    "h5py"
]

[project.scripts]

[project.urls]
homepage = "https://github.com/aistairc/aiaccel"
documentation = "https://aiaccel.readthedocs.io"
repository = "https://github.com/aistairc/aiaccel"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-subprocess",
    "undecorated",
]
github-actions = [
    "pytest-github-actions-annotate-failures",
]
dev = [
    "ruff",
    "mypy",
    "myst-parser",
    "pre-commit",
    "sphinx",
    "sphinxcontrib-jquery",
    "sphinx-intl",
    "sphinx-fontawesome",
    "sphinx-rtd-theme",
]

[tool.setuptools]
include-package-data = true
packages = [
    'aiaccel',
    'aiaccel.sampler',
]

[tool.setuptools.package-data]
aiaccel = ["default_config.yaml"]

[tool.ruff]
line-length = 120
target-version = "py38"
fix = true
select = [
    "E", # all errors
    "W", # all warnings
    "B", # all bugs
    "I", # import order
    "C", # code style
]
ignore = [
    "E203", # exclude colon whitespace error
]

[tool.mypy]
python_version="3.8"
install_types = true
non_interactive = true
ignore_missing_imports = true
warn_unused_configs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_reexport = true
strict_equality = true
strict_concatenate = true
