environment:
  result_dir: ./architecture_search_results  # A path to directory where search results are saved.
  device_ids: null  # Indices of GPU for parallel processing.
  num_workers: 9  # The number of workers for dataloader.

dataset:
  name: cifar10  # imagenet or cifar10 or cifar100
  path: ../data
  num_search_classes: 10  # The number of data classes for supernet train and architecture search.
  num_data_architecture_search: 10000  # The number of data for architecture search. Others are used in supernet train.

nas:
  search_space: proxyless
  num_epochs_supernet_train: 2 #60
  num_epochs_architecture_search: 2 #60
  seed: 42
