dataset:
  name: cifar10  # imagenet or cifar10 or cifar100
  num_data_architecture_search: 10000  # The number of data for architecture search. Others are used in supernet train.
  num_search_classes: 10  # The number of data classes for supernet train and architecture search.
  path: ../data
  retrain:
    train: ../data
    test: ../data

environment:
  device_ids: null
  gpus: 1 # The number of GPUs
  num_workers: 9  # The number of workers for dataloader.
  result_dir: ./architecture_search_results  # A path to directory where search results are saved.

nas:
  num_epochs_architecture_search: 2 #60
  num_epochs_supernet_train: 2 #60
  num_epochs_retrain: 2 #60
  search_space: proxyless
  search_space_config_path: "./"
  seed: 42
  skip_architecture_search: false
  skip_retrain: false
  skip_train: false
  type: separate  # simultaneous or separate

retrain:
  hyperparameters:
    base_lr: 0.01
    batch_size: 64
    momentum: 0.0
    num_epochs: 10
    weight_decay: 0.0

trainer:
  accelerator: mps
  enable_model_summary: false
  enable_progress_bar: false
  logger: false
  strategy: auto